# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: node-fiap
#   namespace: rms
# spec:
#   selector:
#     matchLabels:
#       app: node-fiap
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: node-fiap
#     spec:
#       containers:
#         - name: node-fiap-container
#           image: nginxdemos/hello:latest
#           imagePullPolicy: IfNotPresent
#           ports:
#             - containerPort: 3000
#           envFrom:
#             - configMapRef:
#                 name: node-fiap-configmap
#           # livenessProbe:
#           #   httpGet:
#           #     path: /clients
#           #     port: 3000
#           #   periodSeconds: 10
#           #   failureThreshold: 3
#           #   #initialDelaySeconds: 20
#           # readinessProbe:
#           #   httpGet:
#           #     path: /clients
#           #     port: 3000
#           #   periodSeconds: 10
#           #   failureThreshold: 5
#           #   #initialDelaySeconds: 20

---
apiVersion: v1
kind: Namespace
metadata:
  name: rms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: rms
spec:
  selector:
    matchLabels:
      app: echoserver
  replicas: 1
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: k8s.gcr.io/e2e-test-images/echoserver:2.5
        name: echoserver
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: rms
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  ports:
  - port: 8080
    protocol: TCP
  type: LoadBalancer
  selector:
    app: echoserver