apiVersion: v1
kind: Service
metadata:
  name: svc-db-order
  namespace: rms
  labels:
    app: mysql-fiap
spec:
  type: NodePort
  ports:
    - port: 3306 #porta interna
      nodePort: 30001 #porta para acesso no host
  selector:
    app: mysql-fiap
